# HyprSpace Dwindle Layout Configuration Example
# Place a copy of this config to ~/.aerospace.toml
# Optimized for the dwindle layout - a binary tree layout inspired by Hyprland

# You can use it to add commands that run after AeroSpace startup.
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations work great with dwindle layout
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Accordion padding (not used in dwindle, but kept for layout switching)
accordion-padding = 30

# Dwindle layout as default
# Dwindle creates automatic binary tree splits - each new window splits the focused window
default-root-container-layout = 'dwindle'

# Auto orientation works well with dwindle
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Automatically unhide macOS hidden apps
automatically-unhide-macos-hidden-apps = false

# Keyboard layout
[key-mapping]
    preset = 'qwerty'

# Gaps configuration - dwindle looks great with gaps
# Recommended: 8-12px for a clean, modern look
[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       10
    outer.bottom =     10
    outer.top =        10
    outer.right =      10

# Main binding mode
[mode.main.binding]
    # Terminal (optional)
    # alt-enter = '''exec-and-forget osascript -e '
    # tell application "Terminal"
    #     do script
    #     activate
    # end tell'
    # '''

    # Layout commands
    # Dwindle is the primary layout, but allow switching to others
    alt-d = 'layout dwindle'
    alt-t = 'layout tiles horizontal vertical'
    alt-a = 'layout accordion horizontal vertical'
    alt-s = 'layout scroll'

    # Balance sizes - IMPORTANT for dwindle layout
    # Use this to reset window sizes to equal proportions
    alt-equal = 'balance-sizes'

    # Focus navigation (vim-style)
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    # Move windows (vim-style with shift)
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # Resize windows
    # In dwindle, resize adjusts the split ratio
    alt-minus = 'resize smart -50'
    alt-shift-equal = 'resize smart +50'

    # Workspace navigation
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'

    # Move windows to workspaces
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'

    # Workspace back-and-forth
    alt-tab = 'workspace-back-and-forth'

    # Move workspace between monitors
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # Enter service mode
    alt-shift-semicolon = 'mode service'

# Service mode for special operations
[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # Reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle floating
    backspace = ['close-all-windows-but-current', 'mode main']

    # Balance sizes shortcut in service mode
    b = ['balance-sizes', 'mode main']

    # Join windows (create containers)
    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']
