# HyprSpace Scroll Layout Configuration Example
# Place a copy of this config to ~/.aerospace.toml
# Optimized for the scroll layout - carousel-style with centered focused window

# You can use it to add commands that run after AeroSpace startup.
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations work well with scroll layout
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Accordion padding (not used in scroll, but kept for layout switching)
accordion-padding = 30

# Scroll layout as default
# Scroll creates a carousel layout where the focused window is centered at 80% width
# with 10% peek margins showing neighboring windows
default-root-container-layout = 'scroll'

# Horizontal orientation recommended for scroll layout
default-root-container-orientation = 'horizontal'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Automatically unhide macOS hidden apps
automatically-unhide-macos-hidden-apps = false

# Keyboard layout
[key-mapping]
    preset = 'qwerty'

# Gaps configuration for scroll layout
# Smaller gaps work well with the carousel effect
[gaps]
    inner.horizontal = 5
    inner.vertical =   5
    outer.left =       5
    outer.bottom =     5
    outer.top =        5
    outer.right =      5

# Main binding mode
[mode.main.binding]
    # Terminal (optional)
    # alt-enter = '''exec-and-forget osascript -e '
    # tell application "Terminal"
    #     do script
    #     activate
    # end tell'
    # '''

    # Layout commands
    # Scroll is the primary layout, but allow switching to others
    alt-s = 'layout scroll'
    alt-t = 'layout tiles horizontal vertical'
    alt-a = 'layout accordion horizontal vertical'
    alt-d = 'layout dwindle'

    # Focus navigation - optimized for horizontal scrolling
    # Left/right are primary navigation in scroll layout
    alt-h = 'focus left'
    alt-l = 'focus right'
    alt-j = 'focus down'
    alt-k = 'focus up'

    # Alternative arrow key navigation for scroll
    alt-left = 'focus left'
    alt-right = 'focus right'
    alt-down = 'focus down'
    alt-up = 'focus up'

    # Move windows
    alt-shift-h = 'move left'
    alt-shift-l = 'move right'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'

    # Alternative arrow keys for moving
    alt-shift-left = 'move left'
    alt-shift-right = 'move right'
    alt-shift-down = 'move down'
    alt-shift-up = 'move up'

    # Resize windows
    # In scroll layout, resize adjusts the custom width of focused window
    # Default is 80% screen width, but you can resize to any width
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    # Fine-grained resize for precise control
    alt-shift-minus = 'resize smart -25'
    alt-shift-equal = 'resize smart +25'

    # Workspace navigation
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'

    # Move windows to workspaces
    cmd-shift-1 = 'move-node-to-workspace 1'
    cmd-shift-2 = 'move-node-to-workspace 2'
    cmd-shift-3 = 'move-node-to-workspace 3'
    cmd-shift-4 = 'move-node-to-workspace 4'
    cmd-shift-5 = 'move-node-to-workspace 5'
    cmd-shift-6 = 'move-node-to-workspace 6'
    cmd-shift-7 = 'move-node-to-workspace 7'
    cmd-shift-8 = 'move-node-to-workspace 8'
    cmd-shift-9 = 'move-node-to-workspace 9'

    # Workspace back-and-forth
    alt-tab = 'workspace-back-and-forth'

    # Move workspace between monitors
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # Enter service mode
    alt-shift-semicolon = 'mode service'

# Service mode for special operations
[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # Reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle floating
    backspace = ['close-all-windows-but-current', 'mode main']

    # Reset window sizes to default (80% width)
    b = ['balance-sizes', 'mode main']

    # Join windows (create containers)
    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']
